# Generated by Django 4.2.4 on 2023-10-04 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayrequest',
            name='approved',
            field=models.BooleanField(null=True, verbose_name='Approved?'),
        ),
        migrations.AddField(
            model_name='holidayrequest',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holidayrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holidayresponse',
            name='responded_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='holiday.holidayrequest'),
        ),
    ]
