# Generated by Django 4.2.4 on 2023-10-04 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_holidayrequest_approved_holidayrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayrequest',
            name='requested_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Requested Date'),
            preserve_default=False,
        ),
    ]
