# Generated by Django 4.2.4 on 2023-10-05 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0003_holidayrequest_requested_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HolidayResponse',
        ),
    ]
