# Generated by Django 4.2.4 on 2023-10-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='approval_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_group', to='users.group'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='belonging_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belonging_group', to='users.group'),
        ),
    ]
